// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhAKI_VvbEyHbX3NdNquO55p_JNc4jgqw',
    appId: '1:149447499607:web:1d94e1744e71df72c1a812',
    messagingSenderId: '149447499607',
    projectId: 'neighborhood-e3705',
    authDomain: 'neighborhood-e3705.firebaseapp.com',
    storageBucket: 'neighborhood-e3705.firebasestorage.app',
    measurementId: 'G-N5Z0018M37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEAlwb2JMw2UtElymWbTE7frzfzCrq2sw',
    appId: '1:149447499607:android:ed99d672b1f123e7c1a812',
    messagingSenderId: '149447499607',
    projectId: 'neighborhood-e3705',
    storageBucket: 'neighborhood-e3705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_kRpQ3KfAFReXxziC072svvgGhRDgfU',
    appId: '1:149447499607:ios:bd6a8a991f6fb806c1a812',
    messagingSenderId: '149447499607',
    projectId: 'neighborhood-e3705',
    storageBucket: 'neighborhood-e3705.firebasestorage.app',
    iosBundleId: 'com.example.neighborhoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_kRpQ3KfAFReXxziC072svvgGhRDgfU',
    appId: '1:149447499607:ios:bd6a8a991f6fb806c1a812',
    messagingSenderId: '149447499607',
    projectId: 'neighborhood-e3705',
    storageBucket: 'neighborhood-e3705.firebasestorage.app',
    iosBundleId: 'com.example.neighborhoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhAKI_VvbEyHbX3NdNquO55p_JNc4jgqw',
    appId: '1:149447499607:web:7ed198b26c0a4944c1a812',
    messagingSenderId: '149447499607',
    projectId: 'neighborhood-e3705',
    authDomain: 'neighborhood-e3705.firebaseapp.com',
    storageBucket: 'neighborhood-e3705.firebasestorage.app',
    measurementId: 'G-RKX062TR05',
  );

}